### ISSUE TITLE
Problems posting A record with view

### ISSUE THREAD

**Issue by upsam** [govdelivery/infoblox#49]
This is what we did to fix the problem on our end. Otherwise we hit errors. 

On _some_ record types, the Infoblox API documentation says that `view`
can not be updated, but the Infoblox gem defines them as `remote_attr_accessor`
attributes, which are sent in both POST and PUT requests. Shuffle
that around.

https://ipam.illinois.edu/wapidoc/objects/record.a.html
Infoblox::Arecord.remote_attrs.delete(:view)
Infoblox::Arecord.remote_post_attrs.push(:view)

**Comment by teaforthecat** [comment]
That is interesting. I see in the readme that there is a mention of this: ```a_record.view     = nil```, I suppose setting it to nil would be another work around. So, if I'm understanding this correctly, if the `:view` attribute is moved to `:remote_post_attrs` the view will be sent on a Post but not on a Put, and that is the desired behavior because the view can be set when creating an object, but can't be changed thereafter. Am I getting that right?

**Comment by upsam** [comment]
Yep, that does seem to be correct.

**Comment by teaforthecat** [comment]
@upsam version 2.0.2 has been pushed to Rubygems with this fix. Thanks!

**Comment by upsam** [comment]
Much appreciated. Also if you like you could leave an address for us to direct beer payment.
